const fs=require('fs');
function ok(v,m){if(!v)throw new Error(m)}
const src=fs.readFileSync('hd24-followup.js','utf8');
ok(src.includes("if(!cPlant)throw new Error(`Plant column not found: ${ws.name}`)"),'Plant header must be mandatory');
ok(src.includes("if(!cMonth)throw new Error(`Target Month column not found: ${ws.name}`)"),'Target Month header must be mandatory');
ok(src.includes("?'ulsan':''"),'unknown plant must fail closed after recognizing Ulsan/India/Brazil');
ok(!src.includes("?'india':pkey()"),'unknown plant must not fall back to current plant');
ok(src.includes("rawMonth=val(cMonth),targetMonth=Number(rawMonth)"),'target month must come from workbook');
ok(!src.includes("targetMonth=Number(val(cMonth))||month()"),'invalid month must not fall back to analysis month');
ok(src.includes("!Number.isInteger(targetMonth)"),'target month must be integer');
ok(src.includes("targetMonth<=12"),'target month must be constrained to a valid workbook month');
ok(src.includes("pending.some(x=>x.plant===plant&&(Number(x.targetYear)||2026)===targetYear&&x.targetMonth===targetMonth"),'same-file staged duplicate must be blocked within target year');
ok(/const\s+list=load\(REPLY_KEY\),pending=\[\]/.test(src),'multi-sheet replies must stage before commit');
ok(src.includes("list.unshift(...pending.reverse());save(REPLY_KEY,list.slice(0,4000))"),'staged replies must commit once after workbook validation');
ok(src.includes("replySequence:prev.length+pending.filter(y=>y.plant===plant&&y.targetMonth===targetMonth&&norm(y.kpiEn||y.kpi)===key).length+1"),'second replies must increment sequence within plant/month/KPI');
ok(src.includes("const duplicate=prev.some(sameReply)||pending.some"),'duplicate reply must check persisted and staged rows');
ok(src.includes("function replyHistoryFor(r)")&&src.includes("norm(h.kpiEn||h.kpi)===k"),'recurrence history must remain KPI scoped');
ok(src.includes("isRecurrence:same>=2"),'Repeated Issue requires at least two similar causes');
ok(src.includes("const sent=xs.filter(x=>x.status==='sent'||!!x.sentAt)"),'actual sent mail must win reply anchor selection');
ok(src.includes("if(sent)return sent"),'sent anchor must take precedence over later package/prepared events');
console.log('HD24 FOLLOWUP IMPORT FAIL-CLOSED + ATOMIC/SEQUENCE/MAIL-ANCHOR PASS');
