const fs=require('fs');
function ok(v,m){if(!v)throw new Error(m)}
const src=fs.readFileSync('hd24-history-view.js','utf8');
ok(src.includes("const status=confirmed?'실제 발송':packaged?'Outlook 패키지 다운로드'"),'mail status precedence missing');
ok(src.includes("if(confirmed){g.count+=1;sequence=g.count}"),'mail sequence must advance only for confirmed sends');
ok(src.includes("let sequence=''"),'preview/package events must remain unnumbered');
ok(src.includes("const replyGroups=[]"),'legacy reply chronological sequence fallback missing');
ok(src.includes("sequence:r.replySequence||g.count"),'replySequence precedence missing');
ok(src.includes("latestReply.isRecurrence===true||same>=2"),'latest recurrence state missing');
ok(src.includes("Repeated Issue x"),'Repeated Issue wording missing');
ok(src.includes("r.isRecurrence===true||same>=2"),'timeline recurrence state missing');
ok(src.includes("Outlook .eml 생성·다운로드 · 실제 발송 여부 미확인"),'package must not imply actual send');
ok(src.includes("kpiMails.slice().sort((a,b)=>String(eventTime(a,'mail')).localeCompare(String(eventTime(b,'mail')))"),'mail timeline must sequence chronologically per KPI');
ok(src.includes("replies.slice().sort((a,b)=>String(eventTime(a,'reply')).localeCompare(String(eventTime(b,'reply')))"),'reply timeline must sequence chronologically per KPI');
ok(src.includes("return events.sort((a,b)=>String(b.time).localeCompare(String(a.time)))"),'combined timeline must display newest event first without changing sequence numbers');
ok(src.includes("e.sequence?`${esc(e.sequence)}차`:'-'"),'non-send timeline events must not render as dash sequence');
ok(src.includes("mailCount:ms.filter(x=>!!x.sentAt).length"),'summary mail count must include confirmed sends only');
ok(src.includes("latestSent=ms.find(x=>!!x.sentAt)||{}"),'latest confirmed send must survive newer preview');
ok(src.includes("sentAt:latestSent.sentAt||''"),'summary actual-send timestamp must come from latest confirmed send');
ok(src.includes("const latestTime=r=>[r.replyAt,r.sentAt,r.openedAt,r.preparedAt].filter(Boolean).sort().pop()||''"),'KPI summary rows must sort by latest event across reply/send/open/preview');
ok(src.includes("else if(f.s==='packaged')rows=rows.filter(r=>r.packagedAt)"),'summary packaged filter missing');
ok(src.includes("else if(f.s==='opened')rows=rows.filter(r=>r.openedAt&&!r.sentAt&&!r.packagedAt)"),'legacy-opened filter must exclude Outlook packages');
console.log('HD24 HISTORY VIEW REGRESSION PASS');
