const fs=require('fs');
function ok(cond,msg){if(!cond)throw new Error(msg)}
const src=fs.readFileSync('hd24-action-export.js','utf8');
const guard=fs.readFileSync('hd24-action-cycle-guard.js','utf8');
const loader=fs.readFileSync('hd24-ui-v3.js','utf8');
const refresh=fs.readFileSync('refresh-runtime.html','utf8');
ok(src.includes('hd24SafeReflectSuccessSignature'),'must require safe-reflect success signature');
ok(src.includes('검증반영본'),'must capture only verified reflected workbook downloads');
ok(src.includes('applyKpiActionColumn'),'must call approved workbook postprocessor');
ok(src.includes("/\\.xlsm$/i.test(master.name)"),'must fail closed for XLSM macro preservation');
ok(src.includes('hd24-action-export-complete'),'must emit completion event');
ok(src.includes('analysisMutationSeen'),'must track a post-judge result-card mutation');
ok(src.includes('!analysisMutationSeen'),'must block action export until post-judge mutation is observed');
ok(src.includes('analysisReadySignature!==sig||analysisReadyCycle!==workCycle'),'must require fresh-analysis readiness for current upload cycle');
ok(src.includes('results.filter(r=>Number(r.month)===horizon)'),'must require current-month analysis results');
ok(src.includes('triggerCycle===currentCycle()'),'analysis mutation must belong to current upload cycle');
ok(src.includes('captureCycle!==currentCycle()||signature()!==sig'),'safe workbook capture must reject stale async completion');
ok(src.includes("if(workCycle!==currentCycle()||signature()!==sig)throw new Error('stale action-export cycle after workbook load')"),'workbook load must reject stale cycle');
ok(src.includes("if(workCycle!==currentCycle()||signature()!==sig)throw new Error('stale action-export cycle after workbook write')"),'workbook write must reject stale cycle');
ok(src.includes('cycle:workCycle'),'completion event must carry upload cycle');
ok(guard.includes('stopImmediatePropagation'),'cycle guard must stop stale completion propagation');
ok(guard.includes('eventCycle!==currentCycle'),'cycle guard must compare event/current cycles');
ok(loader.includes('kpi-action-classifier.js?v=23'),'loader must include classifier v23');
ok(loader.includes('kpi-action-workbook.js?v=23'),'loader must include workbook v23');
ok(loader.includes('hd24-action-export.js?v=27'),'loader must include action export v27');
ok(loader.includes('hd24-action-cycle-guard.js?v=1'),'loader must include action cycle guard v1');
const exportPos=loader.indexOf('hd24-action-export.js?v=27');
const guardPos=loader.indexOf('hd24-action-cycle-guard.js?v=1');
const watchdogPos=loader.indexOf('hd24-action-export-watchdog.js?v=1');
const followPos=loader.indexOf('hd24-followup-sync.js?v=8');
ok(exportPos>=0&&guardPos>exportPos,'cycle guard must load after action export producer');
ok(watchdogPos>guardPos,'cycle guard must load before watchdog consumer');
ok(followPos>guardPos,'cycle guard must load before follow-up consumer');
ok(refresh.includes('hd24-action-export.js?v=27'),'refresh helper must preload action export v27');
ok(refresh.includes('hd24-action-cycle-guard.js?v=1'),'refresh helper must preload action cycle guard v1');
console.log('PASS kpi-action-export v27 upload-cycle fail-closed assertions + consumer load order');