const fs=require('fs');
function ok(cond,msg){if(!cond)throw new Error(msg)}
const src=fs.readFileSync('hd24-action-export.js','utf8');
const loader=fs.readFileSync('hd24-ui-v3.js','utf8');
const refresh=fs.readFileSync('refresh-runtime.html','utf8');
ok(src.includes('hd24SafeReflectSuccessSignature'),'must require safe-reflect success signature');
ok(src.includes('검증반영본'),'must capture only verified reflected workbook downloads');
ok(src.includes('applyKpiActionColumn'),'must call approved workbook postprocessor');
ok(src.includes("/\\.xlsm$/i.test(master.name)"),'must fail closed for XLSM macro preservation');
ok(src.includes('hd24-action-export-complete'),'must emit completion event');
ok(src.includes('analysisMutationSeen'),'must track a post-judge result-card mutation');
ok(src.includes('!analysisMutationSeen'),'must block action export until post-judge mutation is observed');
ok(src.includes('analysisReadySignature!==sig'),'must require fresh-analysis readiness for current upload signature');
ok(src.includes('results.filter(r=>Number(r.month)===horizon)'),'must require current-month analysis results');
ok(src.includes('if(sig&&sig===triggerSignature&&window.hd24SafeReflectSuccessSignature===sig&&judgeClickedAt)analysisMutationSeen=true'),'mutation must belong to current triggered/safe signature');
ok(loader.includes('kpi-action-classifier.js?v=23'),'loader must include classifier v23');
ok(loader.includes('kpi-action-workbook.js?v=23'),'loader must include workbook v23');
ok(loader.includes('hd24-action-export.js?v=25'),'loader must include action export v25');
ok(refresh.includes('hd24-action-export.js?v=25'),'refresh helper must preload action export v25');
console.log('PASS kpi-action-export v25 fresh-analysis gate assertions');
