// Regression for production HD24 rule-matrix trend scoping.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('hd24-rule-matrix-v1.js', 'utf8');
const ctx = {window:{},document:{dispatchEvent(){}},CustomEvent:class CustomEvent {constructor(type,opts){this.type=type;this.detail=opts.detail;}},Date,Number,Map,Set};
vm.createContext(ctx);
vm.runInContext(source,ctx);
const api = ctx.window.HD24_RULE_MATRIX_V1;
assert.ok(api,'production rule matrix should load');
const row=(plant,year,month,actual,target=100)=>({plant,targetYear:year,targetMonth:month,kpiEn:'WIP compliance rate (Fabrication)',actual,target});
const indiaJul=row('india',2026,7,80);
const brazilAug=row('brazil',2026,8,10);
const indiaAug=row('india',2026,8,90);
assert.equal(api.trend(indiaAug,[indiaJul,brazilAug,indiaAug]).state,'RECOVERING','cross-plant history must not override India trend');
assert.equal(api.trend(brazilAug,[indiaJul,brazilAug]).state,'NO_TREND','Brazil must not inherit India history');
const indiaDec=row('india',2025,12,70);
const indiaJan=row('india',2026,1,80);
assert.equal(api.trend(indiaJan,[indiaJan,indiaDec]).state,'RECOVERING','year boundary must be chronological');
const unscoped=row('',2026,8,90);
assert.equal(api.trend(unscoped,[indiaJul,unscoped]).state,'NO_TREND','missing plant must fail closed');
const next=row('india',2026,9,95);
assert.equal(api.trend(next,[indiaAug,brazilAug,next]).state,'RECOVERING','WIP compliance increases toward target');
const regression=row('india',2026,9,70);
assert.equal(api.trend(regression,[indiaAug,regression]).state,'WORSENING_MISS','WIP compliance decreases away from target');
const changedTarget=row('india',2026,9,90,95);
assert.equal(api.trend(changedTarget,[indiaAug,changedTarget]).state,'TARGET_CHANGED','target revision must not be mislabeled as recovery');
const changedTargetDown=row('india',2026,9,90,80);
assert.equal(api.trend(changedTargetDown,[indiaAug,changedTargetDown]).state,'TARGET_CHANGED','easier target must not create false recovery');
const process=(plant,year,month,actual,target)=>({plant,targetYear:year,targetMonth:month,kpiEn:'Process Defect Rate (Basic Quality, Leakage, FDI, NDT, ISA)',actual,target});
const quality=(plant,year,month,actual,target)=>({plant,targetYear:year,targetMonth:month,kpiEn:'IQ 200 (Initial Quality)',actual,target});
const achievedProcess=process('india',2026,8,1,2);
const missedQuality=quality('india',2026,8,5,3);
const otherPlantQuality=quality('brazil',2026,8,5,3);
assert.equal(api.clusterFindings([achievedProcess,missedQuality]).filter(x=>x.cluster==='QUALITY / PROCESS').length,1,'same-plant quality contradiction must remain detectable');
assert.equal(api.clusterFindings([achievedProcess,otherPlantQuality]).filter(x=>x.cluster==='QUALITY / PROCESS').length,0,'cross-plant quality contradiction must not be generated');
assert.equal(api.clusterFindings([achievedProcess,{...missedQuality,targetYear:2025}]).filter(x=>x.cluster==='QUALITY / PROCESS').length,0,'cross-year quality contradiction must not be generated');
console.log('PASS: 11 plant/year/WIP/target-change/cross-KPI grouping assertions');

const rate=(plant,month,actual,year=2026)=>({plant,targetYear:year,targetMonth:month,kpiEn:'WIP compliance rate (Fabrication)',unit:'%',actual,target:100});
const p=[rate('india',6,100),rate('india',7,100),rate('india',8,100)];
assert.equal(api.plateauReview(p[2],p).state,'MEASUREMENT_REVIEW','three consecutive 100% rates require measurement review');
const z=[rate('india',6,0),rate('india',7,0),rate('india',8,0)];
assert.equal(api.plateauReview(z[2],z).state,'MEASUREMENT_REVIEW','three consecutive 0% rates require measurement review');
const gap=[rate('india',5,100),rate('india',7,100),rate('india',8,100)];
assert.equal(api.plateauReview(gap[2],gap).state,'NON_CONSECUTIVE_HISTORY','missing month must not count as consecutive');
const blank=[rate('india',6,''),rate('india',7,0),rate('india',8,0)];
assert.equal(api.plateauReview(blank[2],blank).state,'INVALID_VALUES','blank must not become zero');
const mixed=[rate('india',6,100),rate('india',7,95),rate('india',8,100)];
assert.equal(api.plateauReview(mixed[2],mixed).state,'NO_PLATEAU','mixed rates must not trigger plateau');
console.log('PASS: 16 production rule-matrix regression assertions');
